config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#launch"

  get 'pages', to: 'pages#home'
  get 'pages/game', to: 'pages#game', as: "game"

  resources :divings, only: %i[new create edit update] do
    resources :participations, only: %i[new create edit update]
  end

  resources :spots, only: %i[index show] do
    resources :divings, only: %i[new create]
  end

  resources :participations, only: %i[index show destroy]
  resources :divings, only: :destroy
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :diving
  has_many_attached :photos
  has_many :presences, :as => :presentable
  has_many :animals, through: :presences
  # accepts_nested_attributes_for :presences

  validates :depth, presence: true
  validates :gas, presence: true
  validates :rating, presence: true
  validates :diving_time, presence: true
  validates :comment, presence: true
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: %i[show edit update destroy]

  def index
    @participations = Participation.where(user: current_user)
    @title = "Your dives"

    if params[:query].present?
      #@participations = @participations..where("title ILIKE ?", "%#{params[:query]}%")
      @participations = @participations.joins(:diving)
                                        .where(diving: {
                                          spot_id: Spot.where("name ILIKE ?", "%#{params[:query]}%")
                                                      .map(&:id)
                                        } )
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: "participations/partials/cards_participations", locals: {participations: @participations}, formats: [:html] }
    end
  end

  def show
  end

  def edit
    @diving = Diving.find(params[:diving_id])
  end

  def update
    params.dig(:participation, :photos).each do |photo|
      @participation.photos.attach(photo)
    end

    respond_to do |format|
      if @participation.update(participation_update_params)
        format.html { redirect_to participation_path, notice: "Your participation was successfully updated." }
        format.json { render :show, status: ok, location: @participation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @diving = Diving.find(params[:diving_id])
    @participation = Participation.new
    @title = "+ ADD A NEW DIVE"
  end

  def create
    @participation = Participation.new(participation_params)
    @participation.user_id = current_user.id
    @participation.diving_id = params[:diving_id]
    if @participation.save
      redirect_to participation_path(@participation)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @participation.destroy

    respond_to do |format|
      format.html { redirect_to participations_path, notice: "Your participation was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_participation
    @participation = Participation.find(params[:id])
  end

  def participation_params
    params.require(:participation).permit(:user_id, :diving_id, :depth, :gas, :rating, :diving_time, :comment, animal_ids: [], photos: [])
  end

  def participation_update_params
    params.require(:participation).permit(:user_id, :diving_id, :depth, :gas, :rating, :diving_time, :comment, animal_ids: [])
  end
end

app/views/participations/edit.html.erb
<% content_for :page_title, "Edit your diving informations :" %>
<div class="background">

  <div class="container">

    <h3 class="spot_name_edit"><%= @participation.diving.spot.name %></h3>

    <%= render 'participations/partials/form_edit_participations', participation: @participation %>

    <br>

    <div>
      <%= link_to "Show this participation", @participation %> |
      <%= link_to "Back to my participations", participations_path %>
    </div>

  </div>

</div>

app/views/participations/index.html.erb
<% content_for :page_title, "Your dives" %>
<div class="background">

  <div class="container">

    <div data-controller="searchbar">

      <%= render 'shared/search_form' %>

      <%#= turbo_frame_tag :participations, target: "_top" do %>
        <div class="container">
          <%= render 'participations/partials/cards_participations', participations: @participations %>
        </div>
      <%# end %>

    </div>

  </div>

</div>

<%= render "shared/tapbar" %>

app/views/participations/new.html.erb
<% content_for :page_title, "Add a dive" %>

<div class="background">

  <div class="container">

    <%= render "participations/partials/form_new_participation" %>

  </div>

</div>

<%= render "shared/tapbar" %>

app/views/participations/show.html.erb
<% content_for :page_title, "Your dive" %>

<div class="background">

  <div class="container pb-3">

    <%# NAME %>
    <div class="particpations-spot-name-title">
    <h2 class="titles">
      <%= @participation.diving.spot.name %>
    </h2>
    </div>

    <%# STARS %>
    <div id="rating">
      <% if @participation.rating %>
        <% (@participation.rating).times do %>
          <i class="fa-solid fa-star" style="color: #d5700e;"></i>
        <% end %>
      <% end %>
    </div>

    <%# SPOT PHOTO %>
    <%= cl_image_tag @participation.diving.spot.photo.key, class: 'show-photo' %>




    <div class="edit-show">
      <div class="titles-show-participations">
        <h6 class="titles">
        <%= (@participation.diving.date).strftime("%d/%m/%Y") %>
      </h6>
      </div>
      <div class="action-icons">
        <%= link_to '<i class="fa-regular fa-pen-to-square" style="color: #0C0150;"></i>'.html_safe, edit_diving_participation_path(@participation.diving, @participation) %>
        <%= link_to '<i class="fa-regular fa-trash-can" style="color: #0C0150;"></i>'.html_safe, participation_path(@participation), data: { turbo_method: :delete, turbo_confirm: "Do you really want to delete this participation?" } %>
      </div>
    </div>



    <div class="stats-show">
        <div class= "logo-show-stats">
          <% if @participation.diving.weather == "Sunny" %>
            <%= '<i class="fa-solid fa-sun fa-lg dive-icon"></i>'.html_safe %>
            <%= "Sunny" %>
          <% elsif @participation.diving.weather == "Windy" %>
            <%= '<i class="fa-solid fa-wind fa-lg dive-icon"></i>'.html_safe %>
            <%= "Windy" %>
          <% elsif @participation.diving.weather == "Cloudy" %>
            <%= '<i class="fa-solid fa-cloud fa-lg dive-icon"></i>'.html_safe %>
            <%= "Cloudy" %>
          <% elsif @participation.diving.weather == "Storm" %>
            <%= '<i class="fa-solid fa-cloud-bolt fa-lg dive-icon"></i>'.html_safe %>
            <%= "Storm" %>
          <% end %>
        </div>

        <div class= "logo-show-stats">
          <i class="fa-solid fa-temperature-low fa-lg dive-icon"></i>
          <%= @participation.diving.temperature %>°C
        </div>


        <div class= "logo-show-stats">
          <i class="fa-solid fa-binoculars fa-lg dive-icon"></i>
          <%= @participation.diving.visibility %>M
        </div>


        <div class= "logo-show-stats">
          <i class="fa-solid fa-arrow-down fa-lg dive-icon"></i>
          <%= @participation.depth %>M
        </div>

        <div class= "logo-show-stats">
          <i class="fa-solid fa-mask-ventilator fa-lg dive-icon"></i>
          <%= (@participation.gas).capitalize %>
        </div>

        <div class= "logo-show-stats">
          <i class="fa-solid fa-stopwatch fa-lg dive-icon"></i>
          <%= @participation.diving_time %> min
        </div>
    </div>

    <div class="comment-species">
      <div class= "stats-school">
        <div class= "logo-show-stats">
          <i class="fa-solid fa-school fa-lg dive-icon"></i>
          <p><%= @participation.diving.school.name %> </p>
        </div>

        <div class= "logo-show-stats">
          <i class="fa-solid fa-user fa-lg dive-icon"></i>
          <p><%= @participation.diving.school.dive_master %></p>
        </div>
      </div>


      <div class= "stats-show species-specific">
        <div class="animals-crossing">
          <p class= "titles"> <%= "Species observed" %> </p>
          <% if @participation.animals %>
            <% @participation.animals.each do |animal| %>
              <%= cl_image_tag animal.photo.key, class: "species-show"%> <%= animal.name %>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class= "show-comments mb-3">
      <p><i class="fa-regular fa-message fa-lg"></i><em><%= @participation.comment%></em></p>
    </div>



    <%# AFFICHAGE PHOTOS SOUVENIRS USER %>
    <% if @participation.photos.attached?  %>
      <div class="stats-show">

        <div class="album-show">
          <div class="titles">
            My photos
          </div>

          <div class="photo-souvenir">
            <% @participation.photos.each do |photo| %>
              <%= cl_image_tag photo.key, class: "photos-container", height: 200, width: 300, crop: :fill %>
            <% end %>
          </div>

        </div>

      </div>
    <% end %>


  </div>
</div>

<%= render 'shared/tapbar' %>