config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#launch"

  get 'pages', to: 'pages#home'
  get 'pages/game', to: 'pages#game', as: "game"

  resources :divings, only: %i[new create edit update] do
    resources :participations, only: %i[new create edit update]
  end

  resources :spots, only: %i[index show] do
    resources :divings, only: %i[new create]
  end

  resources :participations, only: %i[index show destroy]
  resources :divings, only: :destroy
end

app/models/spot.rb
class Spot < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :divings
  has_one_attached :photo
  has_many :presences, :as => :presentable
end

app/controllers/spots_controller.rb
require "json"
require "open-uri"

class SpotsController < ApplicationController
  def index
    @user_spots = current_user.spots
    @markers = @user_spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        marker_html: render_to_string(partial: "spots/partials/my_markers"),
        info_window_html: render_to_string(partial: "spots/partials/info_window", locals: { spot: spot })
      }
    end

    @spots = Spot.where.not(id: @user_spots.map(&:id))

    @other_markers = @spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        marker_html: render_to_string(partial: "spots/partials/other_markers"),
        info_window_html: render_to_string(partial: "spots/partials/info_window", locals: { spot: spot })

      }
    end
    @markers += @other_markers

  end

  def show
    @spot = Spot.find(params[:id])
    @divings = Diving.where(spot_id: params[:id])
  end
end

app/views/spots/index.html.erb
<% content_for :page_title, "Scubapp" %>

<div class="background">

  <div class="container">

    <div data-controller="weather", class="weather">
      <div class="align">
        <p data-weather-target="today", class="space"></p>
        <p data-weather-target="city", class="city"></p>
      </div>

      <div class="temperature">
        <p data-weather-target="temperature"></p>

          <div class="weather-icon">
            <img src="" alt="" data-weather-target="icon">
            <p data-weather-target="description"></p>
          </div>

      </div>

    </div>

    <%= render 'spots/partials/map' %>

  </div>

</div>

<%= render 'shared/tapbar' %>

app/views/spots/show.html.erb
<div class="background">

  <% content_for :page_title, "Welcome to,"%>

    <div class="container pb-3">

      <%# TITLE %>
      <h3 class="titles"> <%= @spot.name %> <i class="fa-solid fa-umbrella-beach" style="color: #557ec3;"></i> </h3>

      <%# SPOT %>
      <div class="spot-description">
        <%= cl_image_tag @spot.photo.key, class:'spot-photo' %>
        <%= @spot.description %>
      </div>

      <%# DIVING LIST %>
      <div class="diving-date-list">
        <h5>Dives registered on this spot :</h5>
            <% @divings.each do |diving| %>
              <li class="list-divings">
                <p> <%= (diving.date).strftime("%d/%m/%Y") %>  <%= link_to '<i class="fa-solid fa-user-plus" style="color: #09339E"></i>'.html_safe, new_diving_participation_path(diving)%> </p>
              </li>
            <% end %>
      </div>

    </div>
</div>

<%= render 'shared/tapbar' %>