config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#launch"

  get 'pages', to: 'pages#home'
  get 'pages/game', to: 'pages#game', as: "game"

  resources :divings, only: %i[new create edit update] do
    resources :participations, only: %i[new create edit update]
  end

  resources :spots, only: %i[index show] do
    resources :divings, only: %i[new create]
  end

  resources :participations, only: %i[index show destroy]
  resources :divings, only: :destroy
end

app/models/spot.rb
class Spot < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :divings
  has_one_attached :photo
  has_many :presences, :as => :presentable
end

app/controllers/spots_controller.rb
require "json"
require "open-uri"

class SpotsController < ApplicationController
  def index
    @user_spots = current_user.spots
    @markers = @user_spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        marker_html: render_to_string(partial: "spots/partials/my_markers"),
        info_window_html: render_to_string(partial: "spots/partials/info_window", locals: { spot: spot })
      }
    end

    @spots = Spot.where.not(id: @user_spots.map(&:id))

    @other_markers = @spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        marker_html: render_to_string(partial: "spots/partials/other_markers"),
        info_window_html: render_to_string(partial: "spots/partials/info_window", locals: { spot: spot })

      }
    end
    @markers += @other_markers

  end

  def show
    @spot = Spot.find(params[:id])
    @divings = Diving.where(spot_id: params[:id])
  end
end

app/views/spots/partials/_info_window.html.erb
<h3><%= spot.name %></h3>
<%= link_to "Visit spot", spot_path(spot), class: "btn btn-primary"%>

app/views/spots/partials/_map.html.erb
<div class="map-container">

  <div style="width: 100%; height: 400px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/spots/partials/_my_markers.html.erb
<%= image_tag "notrelogo.png", height: 30, width: 30, alt: "Logo" %>

app/views/spots/partials/_other_markers.html.erb
<%= image_tag "pink_flag.png", height: 50, width: 50, alt: "Logo" %>