config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#launch"

  get 'pages', to: 'pages#home'
  get 'pages/game', to: 'pages#game', as: "game"

  resources :divings, only: %i[new create edit update] do
    resources :participations, only: %i[new create edit update]
  end

  resources :spots, only: %i[index show] do
    resources :divings, only: %i[new create]
  end

  resources :participations, only: %i[index show destroy]
  resources :divings, only: :destroy
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if current_page?("http://localhost:3000/") || current_page?("https://www.scubapp.org/") || current_page?("http://127.0.0.1:3000/")%>
  <div></div>
<% else %>
  <div class="div-banner container">
    <h2 class="titles"><%= page_title %></h2>
    <div>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in?%>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, id:"avatar", height: 45, width: 45, crop: :fill%>
              <% else %>
                <%= image_tag "user.jpg", id:"avatar", height: 45, width: 45 %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_search_form.html.erb
<%# <div class="container mb-5">
  <div class="searchbar">
    <%= simple_form_for :search, url: participations_path, method: :get, data: { turbo_frame: @participations, searchbar_target: 'form' } do |f| %>
      <%# <div class="search-form-control form-group">
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword",
            data: {action: "keyup->searchbar#submit", searchbar_target: 'searchInput'}
        %>
        <%# <%= button_tag "Search", name: "", class:'btn btn-primary' do %>
          <%# <i class="fas fa-search"></i> Search
        <% end %>
    <%#   </div>
    <% end %>
<%#   </div>
</div> %>


<div class="search-container">
   <%= simple_form_for :search, url: participations_path, method: :get, data: { searchbar_target: 'form' } do |f| %>

      <div class="search-box">
        <button class="btn-search"><i class="fas fa-search"></i></button>
        <input type="text" name="query" class="input-search" placeholder="Type to Search..." data-searchbar-target="input" data-action="keyup->searchbar#submit">
      </div>
  <% end %>
</div>

app/views/shared/_tapbar.html.erb
<div class="bar" data-controller="tapbar">

  <%# HOMEPAGE %>
  <div class="bar-item <%= 'active' if current_page?(pages_path) %> pre-active" >
    <div class="bar-fluid"></div>
    <div class="drop"></div>
    <%= link_to '<i class="fa-solid fa-house"></i>'.html_safe, pages_path, class: "link" %>
  </div>

  <%# INDEX PARTICIPATION %>
  <div class="bar-item <%= 'active' if current_page?(participations_path) %> pre-active" >
    <div class="bar-fluid"></div>
    <div class="drop"></div>
    <a class="link" href="/participations">
      <span class="material-symbols-outlined" style="font-size: 40px;">scuba_diving</span>
    </a>
  </div>

  <%# NEW DIVING %>
  <div class="bar-item <%= 'active' if current_page?(new_diving_path) %> pre-active" >
    <div class="bar-fluid"></div>
    <div class="drop"></div>
    <%= link_to '<i class="fa-sharp fa-solid fa-plus"></i>'.html_safe, new_diving_path, class: "link" %>
  </div>

  <%# MAP %>
  <div class="bar-item <%= 'active' if current_page?(spots_path) %> pre-active" >
    <div class="bar-fluid"></div>
    <div class="drop"></div>
    <%= link_to '<i class="fa-solid fa-map"></i>'.html_safe, spots_path, class: "link" %>
  </div>

  <%# GAME %>
  <div class="bar-item <%= 'active' if current_page?(game_path) %> pre-active" >
    <div class="bar-fluid"></div>
    <div class="drop"></div>
    <%= link_to '<i class="fa-solid fa-fish"></i>'.html_safe, game_path, class: "link" %>
  </div>

</div>